module.exports.END_OF_FILE = function() {};
module.exports.END_OF_FILE.toString = function() {return "END_OF_FILE"};
module.exports.BEGINNING_OF_FILE = function() {};
module.exports.BEGINNING_OF_FILE.toString = function() {return "BEGINNING_OF_FILE"};
module.exports.CCB = function() {}; // }
module.exports.CCB.toString = function() {return "CCB"};
module.exports.COMMA = function() {}; // ,
module.exports.COMMA.toString = function() {return "COMMA"};
module.exports.CP = function() {}; // )
module.exports.CP.toString = function() {return "CP"};
module.exports.CSQUARE = function() {}; // [
module.exports.CSQUARE.toString = function() {return "CSQUARE"};
module.exports.DIVIDE = function() {};// /
module.exports.DIVIDE.toString = function() {return "DIVIDE"};
module.exports.EQ = function() {}; // =
module.exports.EQ.toString = function() {return "EQ"};
module.exports.MINUS = function() {}; // -
module.exports.MINUS.toString = function() {return "MINUS"};
module.exports.OCB = function() {}; // {
module.exports.OCB.toString = function() {return "OCB"};
module.exports.OP = function() {}; // (
module.exports.OP.toString = function() {return "OP"};
module.exports.OSQUARE = function() {}; // [
module.exports.OSQUARE.toString = function() {return "OSQUARE"};
module.exports.PLUS = function() {}; // +
module.exports.PLUS.toString = function() {return "PLUS"};
module.exports.SEMI = function() {}; // ;
module.exports.SEMI.toString = function() {return "SEMI"};
module.exports.STRICTGREATER = function(){}; // >
module.exports.STRICTGREATER.toString = function() {return "STRICTGREATER"};
module.exports.STRICTLESS = function(){}; // <
module.exports.STRICTLESS.toString = function() {return "STRICTLESS"};
module.exports.TIMES = function(){}; // *
module.exports.TIMES.toString = function() {return "TIMES"};
module.exports.EQUALTO = function(){}; // ==
module.exports.EQUALTO.toString = function() {return "EQUALTO"};
module.exports.GREATER = function() {}; // >=
module.exports.GREATER.toString = function() {return "GREATER"};
module.exports.LESS = function() {}; // <=
module.exports.LESS.toString = function() {return "LESS"};
module.exports.NOT = function() {}; // !=
module.exports.NOT.toString = function() {return "NOT"};
module.exports.OR = function() {}; // ||
module.exports.OR.toString = function() {return "OR"};
module.exports.OR = function() {}; // && 
module.exports.OR.toString = function() {return "AND"};
module.exports.RUFF = function() {}; // ruff
module.exports.RUFF.toString = function() {return "RUFF"};
module.exports.RELSE = function() {}; // relse
module.exports.RELSE.toString = function() {return "RELSE"};
module.exports.TRICK = function() {}; // trick
module.exports.TRICK.toString = function() {return "TRICK"};
module.exports.TREAT = function() {}; // trick
module.exports.TREAT.toString = function() {return "TREAT"};
module.exports.WHILE = function() {}; // while
module.exports.WHILE.toString = function() {return "WHILE"};
module.exports.BOOLEAN = function() {}; // true | false
module.exports.BOOLEAN.toString = function() {return "BOOLEAN"};
module.exports.ID = function() {};
module.exports.ID.toString = function() {return "ID"};
module.exports.INT = function() {};
module.exports.INT.toString = function() {return "INT"};
module.exports.STRING = function() {};
module.exports.STRING.toString = function() {return "STRING"};
module.exports.UNKNOWN = function() {};
module.exports.UNKNOWN.toString = function() {return "UNKNOWN"};
